//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule_designer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_type:IEntity
    {
        public activity_type()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int Id { get; set; }
        public string type_name { get; set; }
    
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
