//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule_designer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule:IEntity
    {
        public int Id { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public int type { get; set; }
        public int @class { get; set; }
    
        public virtual activity_class activity_class { get; set; }
        public virtual activity_type activity_type { get; set; }
    }
}
